# Generated by Django 4.0.2 on 2022-02-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpsPublicados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_query', models.IntegerField()),
                ('ip_status', models.CharField(max_length=40)),
                ('ip_country', models.CharField(max_length=40)),
                ('ip_countryCode', models.CharField(max_length=40)),
                ('ip_region', models.CharField(max_length=40)),
                ('ip_regionName', models.CharField(max_length=40)),
                ('ip_city', models.CharField(max_length=40)),
                ('ip_zip', models.CharField(max_length=40)),
                ('ip_lat', models.IntegerField()),
                ('ip_lon', models.IntegerField()),
                ('ip_timezone', models.CharField(max_length=40)),
                ('ip_isp', models.CharField(max_length=40)),
                ('ip_org', models.CharField(max_length=40)),
                ('ip_as', models.CharField(max_length=40)),
            ],
        ),
    ]
